### PR TITLE
I6 add long term average graph

### LINKED ISSUE #6: Add a Long Term Average Graph
The [data API ](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/api/data.py)in the Climate Explorer backend opens a collection of files that all fit certain criteria - same variable, same ensemble, same model, same emissions scenario, same seasonal or monthly timestamp. The files differ in that they represent different past and future time periods, and show the projected change of some climate measure over time. They can be shown on a graph like this:

long-term-average-graph

We would like to add a graph like this to the salmon data viewer.

Steps to add this graph:

- [x]  First, get the salmon data viewer working on your workstation. This process isn't documented yet, you'll have to talk to @corviday 

- [x]  The javascript front end needs to be able to request the data from the backend. Add a function to `src/data-services/pcex-backend.js` that accesses the `data` API. This function can be modeled on `testDataRequest()`, perhaps call it `testLongTermAverageDataRequest()`. You will need to hardwire most of the parameters required by the `data` API (linked above) in the function, since data selection isn't finished yet. This function should access [this URL](https://services.pacificclimate.org/pcex/api/data?ensemble_name=ce_files&model=PCIC12&variable=tasmax&emission=historical,rcp85&timescale=monthly&time=5&area=POLYGON+((-129.553223+51.019694,+-127.905273+51.105143,+-126.77002+50.653483,+-124.865723+49.896647,+-124.450684+49.457194,+-123.4375+49.164225,+-122.77832+48.614909,+-122.86377+48.212077,+-123.425293+48.151042,+-125.073242+48.480632,+-127.954102+48.907878,+-129.553223+51.019694))), with two exceptions. First of all, like testDataRequest(), your function should accept an `area` parameter (the watershed the user will choose),  secondly, your ce_ensmble parameter should be `scip_files`, the ensemble for the salmon tool.
- [x]  Create a new folder and react component called `LongTermAverageGraph` and add it to `DataController` next to the `AnnualCycleGraph`. This component can be generally modeled on the `AnnualCycleGraph` component, and should do the same tasks - fetch data from the backend, and when the data arrives, format it into a graph, and display the graph. The graph library we are using is `plotly`, if you need to look up how to do anything.

### PR DESCRIPTION
**Pull request by helfy18**
Add a long-term average graph to the web tool. resolves #6.

### CODE REVIEW

File: src/components/DataController/DataController.js [hunk 1]
```diff
@@ -31,12 +37,14 @@ function DataController({currentRegionBoundary}) {
...
       }
-  }  
+  }  */
 
   return (
     <div className="DataController">
         <br/>
         {monthlyTimeSeries ? <AnnualCycleGraph annualData={monthlyTimeSeries}/> : "No Data Available"}
+        <br/>
+        {longTermTimeSeries ? <LongTermAverageGraph longTermData={longTermTimeSeries}/> : "No Data Available"}
```
Comment (corviday) [inline src/components/DataController/DataController.js:47]: Since we have two graphs now, could we edit the text here to be more specific and say which data was missing, instead of repeating "No Data Available" twice?

File: src/components/LongTermAverageGraph/LongTermAverageGraph.js [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+        })
+        return orderedValues;
+    }
+
+    function longTermTimeSeries() {
+        if(longTermData === null){
+            return []
+        }
+        else {
+            //TODO: fix this, order is not guarenteed
```
Comment (corviday) [inline src/components/LongTermAverageGraph/LongTermAverageGraph.js:39]: This comment is incorrect - you _did_ fix the ordering issue.

File: src/data-services/pcex-backend.js [hunk 3]
```diff
@@ -43,4 +43,26 @@ export function testDataRequest(area) {
     }
   )
   .then(response => response.data);
-}
\ No newline at end of file
+}
+
+export function testLongTermAverageDataRequest(area) {
+    // accept only a specified area -
+    // always gets data from the same file.
```
Comment (corviday) [inline src/data-services/pcex-backend.js:50]: This isn't correct - this API gets data from several files. Maybe change "same file" to "same set of files".

File: src/components/LongTermAverageGraph/LongTermAverageGraph.js [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+const Plot = createPlotlyComponent(Plotly);
+
+
+function LongTermAverageGraph({longTermData}) {
+
+    /* data is a temporary variable that represents the data, which are
+     key value pairs. The keys are the date of the measurement, the values
+     are the temperature at that date. The keys will be sorted, and then the
+     temperatures will be matched to the correct years. */
+    let data = longTermData.rXi1p1.data;
```
Comment (corviday) [inline src/components/LongTermAverageGraph/LongTermAverageGraph.js:17]: Unfortunately, we can't rely on the name of the run being `rXi1p1`. Sometimes it will be `r1i1p1` or `r2i1p1` instead. Each time a simulation is run with one of the climate models is run, it gets a different run code like this. Sometimes we have data from several different simulations available.

Instead of assuming the name of the run will always be `r1i1p1`, could you rewrite this so that _no matter what the name of the run is_, its data is loaded?

Sorry I wasn't clear about this requirement - I'm so used to our data, I forget how odd some of it is!

File: src/components/LongTermAverageGraph/LongTermAverageGraph.js [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+    /* data is a temporary variable that represents the data, which are
+     key value pairs. The keys are the date of the measurement, the values
+     are the temperature at that date. The keys will be sorted, and then the
+     temperatures will be matched to the correct years. */
+    let data = longTermData.rXi1p1.data;   
+    const years = keys(data).sort();
+
+    /* function that returns an array of values, which are in the same order as
+     the sorted keys */
+    function matchValues(keys, values) {
```
Comment (corviday) [inline src/components/LongTermAverageGraph/LongTermAverageGraph.js:22]: This function assumes that lodash's keys() and value() functions return things in matching order. That is, you're assuming that if you have an object like this: 
```javascript
const person = {
  firstName: "James",
  lastName: "Hiebert",
};
```

And you do 
```javascript
const k = keys(person);
const v = values(person);
```

you'll get 
```javascript 
=>  k
["firstName", "lastName"]

=> v 
["James", "Hiebert"]
```

but it's entirely possible to end up with:
```javascript
=>  k
["lastName", "firsttName"]

=> v 
["James", "Hiebert"]
```

If you look at the [lodash description of keys()](https://lodash.com/docs/4.17.15#keys) it says "Iteration order is not guarenteed." That is, they may come out in the "right" order in your browser, and in my browser (the graph looks fine to me) and in fact will probably work fine in most people's browsers,  but somewhere out there there's someone using an ancient version of Internet Explorer or something, and they're going to see `lastName` as `James` or see the order of the points on the graph scrambled because `keys()` and `values()` won't be in matching order for them.

Instead of figuring out what value goes with what date by using a list of `values` and assuming it's in the same order as your list of dates, you should be able to just use your ordered list of dates as keys to the original `data` object to get the values out of that object. As a bonus, this will be more efficient.

**Review by corviday — CHANGES_REQUESTED** [review]
This looks really good overall! The graph shows up correctly for me. I have a couple of suggestions, but overall really nice. Good job jumping into a brand new disorganized system with absolutely no documentation whatsoever and finding your own way around it. :)

longtermgraph

File: src/components/LongTermAverageGraph/LongTermAverageGraph.js (hunk 4 above)
Comment (corviday) [reply src/components/LongTermAverageGraph/LongTermAverageGraph.js:17]: Actually, could you add the simulation code to the title of the graph as well?

File: src/components/LongTermAverageGraph/LongTermAverageGraph.js [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+    
+    var dataArray = entries(longTermData);
+    var data = [];
+    var graphTitle = "Mean Long Term Maximum Temperature: ";
+    
+    // Assert that longTermData is formatted as expected and extract important info
+    if (dataArray.length >= 1) {
+        if (dataArray[0].length == 2){
+            data = dataArray[0][1].data;
+            graphTitle = graphTitle.concat(dataArray[0][0].toUpperCase());
```
Comment (corviday) [inline src/components/LongTermAverageGraph/LongTermAverageGraph.js:26]: One small change here: please use a javascript template literal instead, they're easier for other people to read.

File: src/components/LongTermAverageGraph/LongTermAverageGraph.js [hunk 7]
```diff
@@ -0,0 +1,82 @@
...
+        }
+    }
+    const years = keys(data).sort();
+    /* function that returns an array of values, which are in the same order as
+     the sorted keys */
+    function matchValues(entries) {
+        let orderedValues = [];
+        years.forEach((year) => {
+            for(const [key, value] of entries) {
+                if (year === key) orderedValues.push(value);
```
Comment (corviday) [inline src/components/LongTermAverageGraph/LongTermAverageGraph.js:36]: Nice! Not exactly the way I would have done it, but a good use of lodash, which is a really nice library.

**Review by corviday — CHANGES_REQUESTED** [review]
One tiny change left, a small matter of style and readability! This look good overall.

**Review by corviday — APPROVED** [review]
Looks good! Go ahead and merge when you're ready!
